### ISSUE TITLE
Can this be used as a Load/Save function ?

### ISSUE THREAD

**Issue by ad48hp** [inkle/Unity-Save-Play-Mode-Changes#2]
If so, could ya modify the code a bit, so it would save it in a file ? (And then put it in a new repository, so people could spend less time searching for it..)
I might try to myself, if it doesn't exist (couldn't be found) maybe yet, and if you don't have time for (any, perhaps ?) reason..

**Comment by tomkail** [comment]
You could, I think! Best of luck!
